services:
  - type: web
    name: ticket-booking-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /shows
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000

databases:
  - name: ticketdb
    databaseName: ticketdb
    user: postgres
    plan: free
    region: oregon
    initialSqlPath: ./sql/schema.sql
